### ISSUE TITLE
[BUG] plugin different version of package

### ISSUE THREAD

**Issue by Levinethan** [yomorun/yomo#142]
### Summary (概要)

when I use cmd "yomo dev", I got some problem

### Steps To Reproduce (复现的步骤)

1.mkdir demo
2.open my IDE goland to open my demo project
3.go mod tidy
4.yomo dev

### Additional Details & Logs (附加的信息和日志)

- Yomo version (版本)1.0.0-3gf175e41 (2021-03-10)
- Yomo error logs (错误日志)Load handle from .so file failure with error: plugin.Open("sl"): plugin was built with a different version of package github.com/yomorun/yomo/pkg/yy3
- Yomo configuration (配置) I got the issue when I enter the cmd "yomo dev",so there`s probably is yomo init config
- Operating system (操作系统)MacOS Catalina v10.15.7
-

**Comment by fanweixiao** [comment]
Thanks @Levinethan

**Comment by xiaojian-hong** [comment]
@Levinethan thanks for your feedback, we found the template in `yomo init` was outdated, you can upgrade the YoMo CLI in the following steps.

```shell
$ GO111MODULE=off go get -u github.com/yomorun/yomo

$ cd $GOPATH/src/github.com/yomorun/yomo

$ make install
```

Could you please also check the `go.mod` file in your demo?
The following is the correct `go.mod` in my local, please note that `replace github.com/yomorun/yomo => ../../yomorun/yomo` is required by YoMo  CLI.

```
module demo

go 1.15

require (
	github.com/reactivex/rxgo/v2 v2.4.0
	github.com/yomorun/y3-codec-golang v1.6.6
	github.com/yomorun/yomo v1.0.0
)

replace github.com/yomorun/yomo => ../../yomorun/yomo
```

Another question, is the demo project under your  `GOPATH` folder? For example, `$GOPATH/src/github.com/Levinethan/demo`.
YoMo requires the serverless app should be placed in `GOPATH`.

**Comment by fanweixiao** [comment]
Hi @Levinethan , does the problem solved?

**Comment by Levinethan** [comment]
yep, It works
