### ISSUE TITLE
Print `UDP Receive Buffer Size` in CLI

### ISSUE THREAD

**Issue by xiaojian-hong** [yomorun/yomo#198]
When running the `CLI`, we need to print `UDP Receive Buffer Size` in the current OS and validate if it doesn't fit the recommended size.

**Comment by xiaojian-hong** [comment]
`2021/02/22 19:35:09 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.` 


Code: https://github.com/lucas-clemente/quic-go/blob/b8f07c728cf901da96ad445306a3190a51b2b399/packet_handler_map.go#L84

**Comment by fanweixiao** [comment]
should provide a readme to indicates how to tune the server for UDP performance for different scenarios, close this issue cause this is not suitable for all.
