### ISSUE TITLE
Count the amount of `data frame` in zipper

### ISSUE THREAD

**Issue by xiaojian-hong** [yomorun/yomo#219]
Count the amount of `data frame` when `zipper` receiving the `data frame` from `source`, and record it in a local file.

**Comment by fanweixiao** [comment]
```bash
$ kill -SIGUSR1 <pid-of-zipper>
............
2021/09/17 10:37:26 [Zipper-1] |> [localhost:9002] localhost:9002
............
```

output to stdout instead of writing to local file.
