### ISSUE TITLE
[BUG] Connect() error tls: no application protocol

### ISSUE THREAD

**Issue by buliangc** [yomorun/yomo#255]
when i run yomo dev.Some problems occur as shown in the figure below,I donn't know how to fix,somebody can give some suggestions,thanks
![image](https://user-images.githubusercontent.com/70619984/141746429-570715a2-d751-459a-9732-22d3ec2f0967.png)

**Comment by fanweixiao** [comment]
@venjiang @xiaojian-hong I'll be better printing the yomo-cli version.

**Comment by xiaojian-hong** [comment]
Hi @buliangc ,

Thanks for reporting this bug, our `dev server` was incompatible with the latest version of YoMo.
We just fixed it, could you try `yomo dev` again?

**Comment by buliangc** [comment]
> Hi @buliangc ,
> 
> Thanks for reporting this bug, our `dev server` was incompatible with the latest version of YoMo. We just fixed it, could you try `yomo dev` again?

>Thanks a lot @xiaojian-hong ,
>
>Thanks for your help. `yomo dev` is working now!!!

**Comment by buliangc** [comment]
>@xiaojian-hong Hello, I find this command on this document is incorrectly typed.Can you cheak it，thanks!
>https://docs.yomo.run/zh/zipper 
>![image](https://user-images.githubusercontent.com/70619984/141976777-db1bea4d-4ffb-4b45-91e1-a6e113f06a89.png)

**Comment by fanweixiao** [comment]
Hi @buliangc , please re-check this, as `source`, should be ran by `go`.

**Comment by buliangc** [comment]
@fanweixiao Thanks.I have re-check this.In another document, two approaches are presented.I can choose to use `go run` or `yomo run`.
![image](https://user-images.githubusercontent.com/70619984/142087534-d6d705a1-795c-4885-b683-f5d4b11884ee.png)

**Comment by xiaojian-hong** [comment]
> @fanweixiao Thanks.I have re-check this.In another document, two approaches are presented.I can choose to use `go run` or `yomo run`. ![image](https://user-images.githubusercontent.com/70619984/142087534-d6d705a1-795c-4885-b683-f5d4b11884ee.png)

Hi @buliangc ,

Yes, you can choose either `go run` (requires the `main()` function, just likes a Golang application) or `yomo run` (just needs the `Handler` as a Serverless function) to run the `stream-function`.
We recommend using `yomo run` because it is simple and lightweight.

**Comment by fanweixiao** [comment]
But as `source` component, should use `go run` only, right?
