### ISSUE TITLE
[BUG]client [NewClient] Error: CRYPTO_ERROR (0x178): tls: no application protoco

### ISSUE THREAD

**Issue by buliangc** [yomorun/yomo#258]
### Summary (概要)
When I run this example, I want to do y3 encoding.There are some problems with the operation.It worked fine when I coded the example in JSON.
>https://github.com/yomorun/yomo-source-example/blob/main/main.go

### Steps To Reproduce (复现的步骤)
I think there might be some error in the execution of this statement.But i don't know how to fix it.Can you give me some advices.thanks a lot.
>cli, err := client.NewSource("yomo-source").Connect(host, port)

![image](https://user-images.githubusercontent.com/70619984/142196570-cfabc91c-9fee-4ef1-861f-4c2f85407342.png)

### Additional Details & Logs (附加的信息和日志)
- github.com/yomorun/yomo v1.2.520 // indirect
- Yomo version (版本)  YoMo CLI version: v0.1.3
- Yomo error logs (错误日志) client [NewClient] Error: CRYPTO_ERROR (0x178): tls: no application protoco
- Yomo configuration (配置) 
- Operating system (操作系统) windows

**Comment by xiaojian-hong** [comment]
Hi @buliangc ,

Thanks for your feedback.
The example `yomo-source-example` was based on the old YoMo version v1.2.520, which is incompatible with the YoMo CLI v0.1.3.
We just upgraded the [yomo-source-example](https://github.com/yomorun/yomo-source-example), you can check out the new codes and try again.

About Y3 encoding, we are using it in the core of YoMo (f.e. [frame](https://github.com/yomorun/yomo/tree/master/core/frame)).
But for `yomo-source` and `yomo-streaming-function`, we recommend using JSON instead of Y3 in YoMo v1.5.

**Comment by buliangc** [comment]
@xiaojian-hong Thank you for helping me with my confusion!
There's one more question I'd like to ask.When i run this [example-noise](https://github.com/yomorun/example-noise) .

I run Docker-compose directly from the tutorial. 
![image](https://user-images.githubusercontent.com/70619984/142409067-b35a9583-af6c-4593-8e42-f6035ded8d2d.png)

But something went wrong.I cheak the docker-compose log.I find `noise-emitter noise-source noise-zipper`can work.But `noise-flow` and `noise-sink` got something wrong. `noise-flow` didn't work at first .So i changed the noise-flow startup command in Docker-compose because the original command is no longer available in the new version.But there will still be mistakes.
![image](https://user-images.githubusercontent.com/70619984/142410049-cdafaaee-6cfc-48c3-aee6-48b0765457b8.png)

![image](https://user-images.githubusercontent.com/70619984/142411670-fb4931a2-4562-4335-83e1-e577f21d0aa1.png)

I guess the version is not compatible, so there is a problem. I'm really sorry to trouble you ,Can you check this example,Thanks a lot!
### Additional Details & Logs (附加的信息和日志)
- Yomo version (版本)  YoMo CLI version: v0.1.3
- Yomo error logs (错误日志) 
- Yomo configuration (配置) 
- Operating system (操作系统) Ubuntu16.04 docker

**Comment by xiaojian-hong** [comment]
@buliangc we just fixed the docker images, you could try the following steps to re-run the example.

1. Go to the local directory which `docker-compose.yaml` locates in.
2. Stop and remove the running services.

```sh
sudo docker-compose stop
sudo docker-compose rm -f
```

3. Update the [docker-compose.yaml](https://raw.githubusercontent.com/yomorun/example-noise/main/docker-compose.yml) in your local.
4. Re-create the services.

```sh
sudo docker-compose up -d
```

feel free to let me know if you have any troubles when using YoMo. :)

**Comment by buliangc** [comment]
@xiaojian-hong Thank you very much!!! I've tried it and it worked!
![image](https://user-images.githubusercontent.com/70619984/142592627-87045e15-87b9-4a59-9e42-76d5292b9ac5.png)

I hope you can update all the codes of this case, so that I can further learn `YoMo`.Thanks a lot. :)

**Comment by xiaojian-hong** [comment]
> @xiaojian-hong Thank you very much!!! I've tried it and it worked! ![image](https://user-images.githubusercontent.com/70619984/142592627-87045e15-87b9-4a59-9e42-76d5292b9ac5.png)
> 
> I hope you can update all the codes of this case, so that I can further learn `YoMo`.Thanks a lot. :)

@buliangc great!
Okay, we will plan to update the codes of our examples to the latest version.
