### ISSUE TITLE
[BUG] Grafana example bug

### ISSUE THREAD

**Issue by buliangc** [yomorun/yomo#260]
### Summary (概要)
I am going to install the Yomo-datasource plugin in Ubuntu Grafana based on the plugin you provided to realize the display of data.
But I tried this [example](https://github.com/yomorun/yomo-websocket-datasource),maybe I did something wrong, ran into two problems.

![image](https://user-images.githubusercontent.com/70619984/142726385-05c18c40-48d4-4302-bd5a-bd120c1af82e.png)

### Steps To Reproduce (复现的步骤)
1. **First**: **In ubuntu**，I followed the tutorial and unzip the [releases link](https://github.com/yomorun/yomo-websocket-datasource/releases)  to Grafana plugins folder. I tried : `yomo-websocket-datasource.zip` and `Source code (tar.gz)`.
Unfortunately, after rebooting Grafana, I couldn't find `YoMo Streams` in the plugin.For comparison, I downloaded a plugin from the Grafana website and unzip to the Grafana plugins folder. Grafana identified it.
So maybe I did something wrong, or it is not the correct version of Linux. So i hope you can give me some advices,thanks a lot!!!

2. **Second**: **In windows**, I unzip the  `yomo-websocket-datasource.zip`  to Grafana plugins folder.Grafana identified it.So great!
![image](https://user-images.githubusercontent.com/70619984/142727360-483e1824-23f8-4943-ae54-9f4aba656997.png)
Then add data source successfully:
![image](https://user-images.githubusercontent.com/70619984/142727924-74bb0edb-39ad-4dd0-9c9b-f75e0e67678d.png)
**But when I want to query data, it shows no data returned:**
![image](https://user-images.githubusercontent.com/70619984/142727889-2b9ad9b5-85d0-45dc-aa37-1e149f21e44b.png)

So that's all the problems I had trying this example. At present, I don't know how to solve these problems,I hope you can give me some advice,thanks a lot!!!

### Additional Details & Logs (附加的信息和日志)

- Yomo version (版本) YoMo CLI version: v0.1.3
- Yomo error logs (错误日志)
- Yomo configuration (配置)
- Operating system (操作系统) ubuntu16.04 and windows

**Comment by xiaojian-hong** [comment]
Hi @buliangc ,
Could you try the Grafana again in windows? It should return data now.

**Comment by buliangc** [comment]
@xiaojian-hong Thanks a lot! I can display the data already!In addition, I would like to ask whether Linux can be supported?
![image](https://user-images.githubusercontent.com/70619984/142870300-393ff8d2-d9b2-4f2d-98af-59c31b8f37b8.png)

**Comment by xiaojian-hong** [comment]
> @xiaojian-hong Thanks a lot! I can display the data already!In addition, I would like to ask whether Linux can be supported? 

Hi @buliangc ,

Yes, Linux can be supported, but you need to add `osdodo-yomo-datasource` to the `allow_loading_unsigned_plugins` in `grafana.in`.

The following are the steps for `Ubuntu`:
1. add `osdodo-yomo-datasource` to the `allow_loading_unsigned_plugins` in  `/etc/grafana/grafana.ini`.
```
allow_loading_unsigned_plugins = osdodo-yomo-datasource
```
![image](https://user-images.githubusercontent.com/48110142/144835698-ef1e746c-04c9-4536-a852-5bdb886365aa.png)

2. restart the `grafara` service
```sh
sudo systemctl restart grafana-server
```

**Comment by buliangc** [comment]
Hi, @xiaojian-hong :
Yeah,I successfully tested this new version  in Grafana on Ubuntu 20.04! Thanks a lot!!!
![image](https://user-images.githubusercontent.com/70619984/145060125-2687fef2-8fb7-4c9e-97ab-f9d0d7f5f5d8.png)
There was also an incident where I entered the wrong plug-in ID at first. The correct type is `yomo-grafana-datasource`, not `osdodo-yomo-datasource`. hhh.Didn't read the tutorial well,my mistake!
![image](https://user-images.githubusercontent.com/70619984/145059806-71eba686-4602-42c2-b0e5-f4f807e2d637.png)

**Comment by xiaojian-hong** [comment]
> Hi, @xiaojian-hong :
> Yeah,I successfully tested this new version in Grafana on Ubuntu 20.04! Thanks a lot!!!
> ![image](https://user-images.githubusercontent.com/70619984/145060125-2687fef2-8fb7-4c9e-97ab-f9d0d7f5f5d8.png)
> There was also an incident where I entered the wrong plug-in ID at first. The correct type is `yomo-grafana-datasource`, not `osdodo-yomo-datasource`. hhh.Didn't read the tutorial well,my mistake!
> ![image](https://user-images.githubusercontent.com/70619984/145059806-71eba686-4602-42c2-b0e5-f4f807e2d637.png)

Great!
Yes, we changed the plugin id in the new version to `yomo-grafana-datasource`.
The id `osdodo-yomo-datasource` in my previous comment was for the old version.
