### ISSUE TITLE
[BUG] example noise

### ISSUE THREAD

**Issue by buliangc** [yomorun/yomo#265]
### Summary

SUMMARY_GOES_HERE
Hello.
I find this [example ](https://github.com/yomorun/example-noise) . Can just run under `YoMo CLI version: v0.05` . When I use `YoMo CLI version: v0.1.3` : it show `yomo-source-noise` unable to connect to `yomo-zipper`. 

### Steps To Reproduce
1. [yomo-zipper](https://github.com/yomorun/yomo-zipper-noise-example) run with `yomo serve -c workflow.yaml`
![image](https://user-images.githubusercontent.com/70619984/144597552-aa76cd13-b130-4a78-bc5c-6180b5ba145e.png)

2. [yomo-source-noise](https://github.com/yomorun/yomo-source-noise-example) run with  `YOMO_SOURCE_MQTT_ZIPPER_ADDR=localhost:9999 YOMO_SOURCE_MQTT_SERVER_ADDR=0.0.0.0:1883 go run main.go`
![image](https://user-images.githubusercontent.com/70619984/144597480-345c2ce1-fafe-4960-b689-290c8b7b5fe6.png)

3. [yomo-source-noise-emitter](https://github.com/yomorun/yomo-source-noise-emitter-example) run with `YOMO_SOURCE_MQTT_BROKER_ADDR=tcp://localhost:1883 \
YOMO_SOURCE_MQTT_PUB_TOPIC=NOISE \
YOMO_SOURCE_MQTT_PUB_INTERVAL=500 \
go run main.go`
![image](https://user-images.githubusercontent.com/70619984/144597626-e631ad75-9ab5-4f22-8d5f-006467929513.png)

Is zipper not supported  `YoMo CLI version: v0.1.3`? [yomo-zipper-noise-example](https://github.com/yomorun/yomo-zipper-noise-example)
![image](https://user-images.githubusercontent.com/70619984/144601689-2c75333f-81e1-4b79-b958-0990e8165b11.png)

Can you give me some advices,I think it applies to `YoMo CLI version: v0.1.3`. Thanks a lot!!! 

### Additional Details & Logs

- Yomo version : YoMo CLI version: v0.1.3
- Yom: error logs
- Yomo configuration
- Operating system: Ubuntu20.04

**Comment by fanweixiao** [comment]
I see is tls issue `no application protocol`, @xiaojian-hong can you check this sometime?

**Comment by buliangc** [comment]
@xiaojian-hong  When I yomo cli version is v0.1.3, an error is reported when it is run.[yomo-source-noise](https://github.com/yomorun/yomo-source-noise-example) will show `no application protocol`. I hope you can check it,thanks a lot!
It helps me a lot. :)

**Comment by xiaojian-hong** [comment]
> @xiaojian-hong When I yomo cli version is v0.1.3, an error is reported when it is run.[yomo-source-noise](https://github.com/yomorun/yomo-source-noise-example) will show `no application protocol`. I hope you can check it,thanks a lot! It helps me a lot. :)

Hi @buliangc ,
yes, the `example-noise` is only working in the YoMo CLI v0.0.5.
We will upgrade this example to the latest version YoMo v1.5.3 and YoMo CLI v0.1.3 soon.

**Comment by xiaojian-hong** [comment]
Hi @buliangc ,
We fixed this issue, could you please checkout the new codes and try again?

**Comment by buliangc** [comment]
I was delayed by something yesterday, so I didn't test it in time. Now, I've tried this example, and it's great. The newer version works better!!! I will continue my YOMO study. Thank you very much. @xiaojian-hong :)

**Comment by xiaojian-hong** [comment]
> I was delayed by something yesterday, so I didn't test it in time. Now, I've tried this example, and it's great. The newer version works better!!! I will continue my YOMO study. Thank you very much. @xiaojian-hong :)

Great! Please feel free to ask us if you meet any problems in YoMo.
