### ISSUE TITLE
[Question] What the differences between YOMO and Apache Flink in applicable scenarios? 

### ISSUE THREAD

**Issue by JinHai-CN** [yomorun/yomo#294]
As title.

**Comment by fanweixiao** [comment]
Hi @JinHai-CN, AF is for big data, distributed in single region, and, is a software. YoMo is a framework, used to create 
 stream processing applications with geo-distributed system arch and low-latency communication.

**Comment by fanweixiao** [comment]
I think AF is built and tuned for big data scenario, different from YoMo.

**Comment by JinHai-CN** [comment]
> I think AF is built and tuned for big data scenario, different from YoMo.

Thank you for your kind reply.
