### ISSUE TITLE
[BUG] Source - On Close() it creates an error within the Zipper

### ISSUE THREAD

**Issue by Nordes** [yomorun/yomo#296]
### Summary

When stopping the source producing data, I try to `source.Close()` then it generates an error on the Zipper instance.

![image](https://user-images.githubusercontent.com/446572/155814514-716fa95e-981e-4f66-b8ad-a90a6266722a.png)

### Steps To Reproduce

1. Create a Zipper (workflow.yaml) and run it
2. Create a source event producer and make it loop `10` times. Once the loops are completed, then do a `source.Close()`
3. Look a the logs coming out from Zipper and you will see two lines with errors.

### Additional Details & Logs

- Yomo version: 0.1.7
- Yomo error logs
- Yomo configuration
- Operating system: Mac

**Comment by venjiang** [comment]
@Nordes Thks. u can use `CLI 0.1.9` and `yomo 1.6.1`, we have fixed this.
