### ISSUE TITLE
[BUG]无法成功执行执行demo中echo.go

### ISSUE THREAD

**Issue by kunwu3** [yomorun/yomo#31]
### Summary (概要)

无法成功执行执行demo中echo.go

### Steps To Reproduce (复现的步骤)

1.在$HOME/go/yomo中执行go mod init yomo
2.执行go get -u github.com/yomorun/yomo
3.按文档创建echo.go
4.执行go run echo.go

### Additional Details & Logs (附加的信息和日志)

- Yomo version: latest
- Yomo error logs:
# command-line-arguments
./echo.go:16:14: cannot use &EchoPlugin literal (type *EchoPlugin) as type plugin.YomoObjectPlugin in argument to yomo.RunDev:
*EchoPlugin does not implement plugin.YomoObjectPlugin (missing Mold method)
- Operating system: Debian 10

**Comment by kunwu3** [comment]
still not working

#information
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
        C:/Users/Victor3/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/unsafe.go:26 +0x20e
exit status 2

**Comment by kunwu3** [comment]
# 解决方法
在$GOPATH/Go-apps/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/unsafe.go 中注释掉第25-30行
 原因盼解答

**Comment by chenjunbiao** [comment]
您好！谢谢你的关注，这个问题在 https://github.com/yomorun/yomo/releases/tag/v0.1.14 已经解决，是因为增加对mold的解析后，demo的例子没有更新，缺乏对Mold()的定义。
`
// Mold describe the struct of `Observed` value
func (p EchoPlugin) Mold() interface{} {
	return ""
}
`
