### ISSUE TITLE
[BUG] Too many mouse pointer icons on web page

### ISSUE THREAD

**Issue by mikeysan** [yomorun/yomo#312]
### Summary

The pointer image on the website is a bit much (I know that's not technical speak but not sure how best to describe it in words). There are two too many, at least. I have attached an image to illustrate what I mean. In addition, the one at the top appears to be cut off. 

### Steps To Reproduce

1. Open Edge Browser on Windows 10
2. Navigate to website (home page)
3. Observe by moving the mouse about.

![image](https://user-images.githubusercontent.com/13338176/160063874-e5df338f-93c5-4ae9-9834-755ceba4efe8.png)

### Additional Details & Logs

- Operating system: Windows 10

**Comment by mikeysan** [comment]
hmm... Not a bug, maybe?
![image](https://user-images.githubusercontent.com/13338176/160066099-ed284218-d8c3-4f2e-ae51-940a113bc24e.png)

I was still looking around when more showed up - and one tried to talk to me. Aliens?

Please close if this is not a bug. I still think it's a bit too much for the home page as all I want to do is learn what the project is about but that could just be me.

**Comment by xiaojian-hong** [comment]
Hi @mikeysan ,
We integrate a [cursor chat](https://github.com/yomorun/react-cursor-chat) feature (like Figma) on our homepage for real-time collaboration.

Maybe it is a little confusing, thanks for your feedback, we will try to improve the user experience on our website.
