### ISSUE TITLE
Update README to indicate Browser support for  Web-Transport

### ISSUE THREAD

**Issue by gedw99** [yomorun/yomo#324]
https://caniuse.com/http3 is the main source of this info.

also https://web.dev/webtransport/#browser-support

Maybe also mention that WebTransport is part of Http/3 as this can confuse people sometimes.

**Comment by fanweixiao** [comment]
Hi @gedw99, YoMo is built on QUIC which is the same underlying protocol of `http3` and `WebTransport`. This means YoMo can bring all the advantages of HTTP/3 to your own backend applications without learning new networking concepts. Just `Serve()` then `Write()` then process way serverless.

WebTransport is not part of HTTP/3, WebTransport is a protocol, it can be ran on top of HTTP/3, HTTP/2, QUIC etc ...
