### ISSUE TITLE
Has yomo provided docs about core/frame?

### ISSUE THREAD

**Issue by xieyuschen** [yomorun/yomo#348]
I have read the [core/frame](https://github.com/yomorun/yomo/tree/master/core/frame) code briefly and I assume it charges for yomo application protocol. Is it the assumption right? If it is, are there some docs about it?

Regards

**Comment by fanweixiao** [comment]
Hi @xieyuschen ,

The [core/frame](https://github.com/yomorun/yomo/tree/master/core/frame) defines wired payloads transferred over YoMo. It's a TLV format codec, called [Y3](https://github.com/yomorun/y3), currently we use [draft-v0](https://github.com/yomorun/y3-codec/blob/draft-01/draft-01.md).

You can join our community here: https://discord.gg/aFrjJnH9 :)

**Comment by xieyuschen** [comment]
> Hi @xieyuschen ,
> 
> The [core/frame](https://github.com/yomorun/yomo/tree/master/core/frame) defines wired payloads transferred over YoMo. It's a TLV format codec, called [Y3](https://github.com/yomorun/y3), currently we use [draft-v0](https://github.com/yomorun/y3-codec/blob/draft-01/draft-01.md).
> 
> You can join our community here: https://discord.gg/aFrjJnH9 :)

ohhh, thanks.
