### ISSUE TITLE
Introduce .env file for config

### ISSUE THREAD

**Issue by wujunzhuo** [yomorun/yomo#349]
### Summary

Currently, YoMo accepts three types of config:  

- config file(`workflow.yaml`)
- env vars 
- command-line args. 

When developers start their serverless, has to:

```bash
yomo dev --zipper-addr=10.10.44.33:9000 --auth-credential=xxxxxxx func.go
```

Due to the lack of complete configuration management, the config process may be time-consuming and error-prone. With this feature developers could config all variables in the .env file.

### Intended Outcome

The config process becomes easier for developers, especially between deploys(such as development, test, and production).

### How will it work?

Developer can add `.env` file in current working directory, then YoMo will read these config variables(prefixed with `YOMO_`) automatically when program started. The file is like the following:

```
YOMO_ZIPPER_ADDR=10.10.44.33:9000
YOMO_LOG_LEVEL=debug
```

then, start with command line: 

```
yomo dev func.go
```

**Comment by luzhenqian** [comment]
You can refer to the practice of nextjs to divide env into env of various environments.
https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables @wujunzhuo

**Comment by wujunzhuo** [comment]
> Below is the practice of nextjs to divide env into env of various environments:
> 
> https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables
> 
> @wujunzhuo

Using multiple env files for different environments is controversial. https://github.com/motdotla/dotenv#should-i-have-multiple-env-files

**Comment by Nordes** [comment]
**Here's my general opinion**
As much as I like the idea of multiple `.env` file, I think the `.env` file should be set during the deployment (CD). For example, in Kubernetes, you can set the secrets to become a `.env` file. This also avoid people committing production, QA, or any other stuff like that in the wild.

Personally, I always start the YoMo server or client using a go app with a `main`. In such case, is the `.env` file be taken and if it's the case, will we have an option to say we want to take it or not?

Example of how I currently start the zipper in the background (I removed the WaitGroup to have less code)
```golang
zipper := yomo.NewZipperWithOptions(
	"SmartZipper",
	yomo.WithZipperAddr("0.0.0.0:9000"),
)
defer zipper.Close()

// configure zipper workflow
zipper.ConfigWorkflow("workflow.yaml") // <== Maybe here we could specify if we loadFromEnv or anything else

// zipper serve
err := zipper.ListenAndServe()
if err != nil {
	panic(err)
}
```

Regarding the client, it would be more or less the same with a default behaviour as mentioned also in the first message.

**Comment by fanweixiao** [comment]
Thanks @Nordes ❤️ . I suggest YoMo changes these:

1. for `zipper`, deprecate `yomo.WithZipperAddr()` in v1.x and remove in v2.x. Introduce `YOMO_ZIPPER_ADDR` env for this setting option. Devops will be easily.
2. YoMo read `.env` at very first stage, hardcoded like `WithOptions()` can override the settings with newer value.

for devops perspective, env is better than command line app parameters and config files.

**Comment by fanweixiao** [comment]
When developers deploy their serverless online, they have to execute: 

`yomo run -d CREDENTIAL_STRING -n IDENTITY -u ZIPPER_ADDR -f example.go`

Developers has to change parameters in different env/profile.

By introducing `.env` file suppport, developers can start the serverless by `yomo run example.go`, that will be more easier and elegant.

Action Items:

- yomo cli will read `.env` in current directory
- only affect on serverless streaming functions
- release `v1.8.3`
