### ISSUE TITLE
implement python and rust client

### ISSUE THREAD

**Issue by SOVLOOKUP** [yomorun/yomo#415]
### Summary

we need python and rust client to support embedded devices better.

**Comment by fanweixiao** [comment]
Hi @SOVLOOKUP, currently, most of YoMo developers deploy their code to a IoT Gateway in IoT. QUIC protocol need tuning when running on embedded devices. If you want to get more ideas about using YoMo in IoT, you can join our community to find more: https://discord.gg/Ugam5qAvHy 😄
