### ISSUE TITLE
platform darwin-arm64 is not supported by curl script

### ISSUE THREAD

**Issue by xunfeng1980** [yomorun/yomo#431]
### Summary
> curl -fsSL https://get.yomo.run | sh

Platform darwin-arm64 is not supported by github.com/yomorun/yomo.

**Comment by fanweixiao** [comment]
Hi @xunfeng1980 , currently, for [writing streaming functions in WebAssembly](https://github.com/yomorun/yomo/tree/master/example/7-wasm) feature, WasmEdge is one of YoMo supports, but this lib makes some CI/CD issue on darwin-arm64 (M1/M2), we are working on solve this by finding a way detach it from compiling, you can have a try on manual compiling `yomo` binary by `make build` on your darwin-arm64: https://github.com/yomorun/yomo/blob/master/Makefile

**Comment by fanweixiao** [comment]
Hi @xunfeng1980 , @woorui completed this, make this script worked, please check!

**Comment by fanweixiao** [comment]
also, related to: https://github.com/bytecodealliance/wasmtime-go/issues/53
