### ISSUE TITLE
Any benchmarks?

### ISSUE THREAD

**Issue by lonnietc** [yomorun/yomo#448]
Hello,

I am researching transport protocols over IP and am seeking something new and extremely fast for high density P2P applications that need ultra-low latency in their communications.

I came across your yomo pages and was wondering how this protocol compares to TCP, UDP, QUIC, and others as far as latency?

Best regards and have a good day

**Comment by fanweixiao** [comment]
Hi @lonnietc, 

- the benchmark of QUIC compared to TCP, I strongly recommend fastly's blog post: https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency. 
- there are kinds of QUIC implementation in different languages, the comparison can be found here: https://www.net.in.tum.de/fileadmin/TUM/NET/NET-2022-07-1/NET-2022-07-1_02.pdf, compared Quiche from Cloudflare, Mvfast from Meta, Msquic from Microsoft, also include quic-go which we use, and other implementations
- hysteria project made a benchmark with TCP Cubic, TCP BBR and kcptun in 2021, can be found here: https://github.com/apernet/hysteria/blob/master/docs/bench/bench.png
- at last, QUIC will perform better when networking goes worse, if you want to test QUIC for your P2P gaming scenario, you can use `tc` to simulate the network conditions like `packet drop rate` and `latency`, there are great posts brief this: https://www.badunetworks.com/traffic-shaping-with-tc/, https://netbeez.net/blog/how-to-use-the-linux-traffic-control/, https://github.com/ngtcp2/ngtcp2/issues/333 and https://man7.org/linux/man-pages/man8/tc.8.html

Hope this helped.
