### ISSUE TITLE
Serverless wasm using wazero

### ISSUE THREAD

**Issue by gedw99** [yomorun/yomo#469]
Would be good to add Wazero to 

https://github.com/yomorun/yomo/tree/master/cli/serverless/wasm

Wazero:

https://github.com/tetratelabs/wazero

it’s pretty stable and I think going to be v1 stable any week now.

it will simplify builds too as there is no cgo .

so a lot of the setup in https://github.com/yomorun/yomo/tree/master/example/7-wasm goes away :) 

works great with tinygo, go, rust, python from my experience

**Comment by fanweixiao** [comment]
Hi @gedw99, thanks for suggestion. Actually, @venjiang  is working on this, on the [`feat/wazero` branch](https://github.com/yomorun/yomo/tree/feat/wazero)

Currently, wazero still has a bug when @venjiang integrate it to yomo: 
 https://github.com/tetratelabs/wazero/issues/1283.

as [wazero will be release 1.0](https://github.com/tetratelabs/wazero/issues/1283#issuecomment-1483017902), We will release a new version to support it 🚀

**Comment by fanweixiao** [comment]
Hi @gedw99, @venjiang just merged `wazero` support to main branch, and updated the README to demonstrate how to handle it, please check: https://github.com/yomorun/yomo#2-write-your-first-stream-function-with-rust-and-webassembly.

Looking forward to your suggestions.

**Comment by gedw99** [comment]
woo - thanks @fanweixiao and @venjiang

Let me have a look and play and then see what suggestions i have.

**Comment by gedw99** [comment]
Just looked at the link... Its rust. Any chance we can have a golang example too ?

sorry but my rust is terrible. I am mostly a golang dev.

**Comment by venjiang** [comment]
Please read the [wasm example documentation](https://github.com/yomorun/yomo/blob/master/example/7-wasm/README.md) , we provide examples in four languages(Rust, C, Go, Zig). 😄

**Comment by gedw99** [comment]
thanks @venjiang !!
