### ISSUE TITLE
[BUG] tinygo not needed

### ISSUE THREAD

**Issue by gedw99** [yomorun/yomo#562]
Go now supports wasi compilation.

I have been using gotip also a d it’s been solid so far.

the go team and Wazero Team got it all working.

so the example wasm stuff should offer using go and not tinygo. Or offer both in the docs.

the gotip is also working.

it’s much much faster at compilation then tinygo too.

**Comment by gedw99** [comment]
https://github.com/yomorun/yomo/tree/master/example/7-wasm Should be updated

**Comment by fanweixiao** [comment]
Thanks for mention this @gedw99, we will try it!

**Comment by gedw99** [comment]
some example golang out there is still broken because of this.

"CallImport" has now gone and been replaced with " //go:wasmimport". 

Here is an example of failing code for browser WASM. I know it does not really apply to the yomorun use cases but anyway.

you need  go1.21rc3  OR gotip...


```sh
                                                                   
go version
go version go1.21rc3 darwin/amd64

gogio -x -target js -o explorer.wasm .
go list -f {{.ImportPath}} .
go list -f {{.Dir}} .
go build -ldflags=-X gioui.org/app/internal/log.appID=org.gioui.explorer -tags= -o explorer.wasm/main.wasm .
gogio: go build -ldflags=-X gioui.org/app/internal/log.appID=org.gioui.explorer -tags= -o explorer.wasm/main.wasm . failed: # gioui.org/x/explorer
/Users/apple/go/pkg/mod/gioui.org/x@v0.0.0-20220812201728-6e5ccb802ed1/explorer/explorer_js.s:6: unrecognized instruction "CallImport"
/Users/apple/go/pkg/mod/gioui.org/x@v0.0.0-20220812201728-6e5ccb802ed1/explorer/explorer_js.s:10: unrecognized instruction "CallImport"
/Users/apple/go/pkg/mod/gioui.org/x@v0.0.0-20220812201728-6e5ccb802ed1/explorer/explorer_js.s:14: unrecognized instruction "CallImport"
asm: assembly of /Users/apple/go/pkg/mod/gioui.org/x@v0.0.0-20220812201728-6e5ccb802ed1/explorer/explorer_js.s failed
```

And here  is  tinygo versus go for wasm, which does relate to Yomorun. Note the GOOS is "wasip1":

Again you need go1.21rc3 OR gotip ...

```sh
tinygo build -o main.wasm -target wasm .

GOOS=wasip1 GOARCH=wasm go build -o main.wasm .
```

**Comment by fanweixiao** [comment]
I see, as go.12 still in RC stage, we will support this after final release.

**Comment by gedw99** [comment]
Ok cool thanks @fanweixiao

**Comment by fanweixiao** [comment]
> Ok cool thanks @fanweixiao 
> 
> 

Currently, tinygo has its limit for go code, for example, tinygo did not support msgpack, that means the 'yomo build' will fail if the code import msgpack package. If we introduce wasip1 as a 0-experimental level for advanced developers, would be a good idea? Wanna have your advise.

**Comment by gedw99** [comment]
This is complex.

wasip1 is incomplete in terms of the Wasm host runner and the compile exporter.  So it’s a multi facetted problem space in the golang world.

https://www.linkedin.com/posts/achille-roussel-b9644b62_go-tinygo-webassembly-activity-7056324342883696640-uEwi

Maybe just stick with go 1.21 but compile wasip1 only using tinygo .
As things improve on go wasip1 then cross test .

wasip2 brings sockets and Wazero , wasi-run and TimeCraft are going to need to allow the host to use sockets to allow guest wasm to talk to the network. Windows support will be shakey. I know TimeCraft are not planning to support it.

So just like linkedIn comments suggest, things are in flux. 

nothing either of use can do except mail down what works and watch the space ..,
