### ISSUE TITLE
Browser equivalent

### ISSUE THREAD

**Issue by gedw99** [yomorun/yomo#599]
The reactive stream bus and factory could be extended to support browsers where you have 3 tiers:

service worker 
Web worker 
Main window.

Then a developer can reuse wasm on the server and browser.

the only thing missing is the factory that would use Message Passing which browsers use to send data across the 3 boundaries list above.

There is a spec / project to try to do this and a few implementations going on. Can dig out the URL later

**Comment by fanweixiao** [comment]
That's a cool idea!

Currently, Yomo focus on wasi, [Presencejs](https://github.com/yomorun/presencejs) would be proper consider this.

Wanna hear more about this topic.

**Comment by gedw99** [comment]
https://github.com/magodo/go-wasmww Is worth a look.

**Comment by fanweixiao** [comment]
> hey @fanweixiao
> 
> https://wanix.sh
> 
> https://github.com/tractordev/wanix
> 
> can run Yomo in browser probably. it can run Hugo in browser for example.

@gedw99 let me check 🎅🏻
