### ISSUE TITLE
 failed to sufficiently increase receive buffer size when `yomo run` on Manjaro

### ISSUE THREAD

**Issue by fanweixiao** [yomorun/yomo#74]
### Summary 

Run `yomo dev` on Manjaro, ` failed to sufficiently increase receive buffer size` error.

### Steps To Reproduce

```bash
~/.../yomo/example >>> ../bin/yomo dev app.go
2020/12/21 13:01:37 Building the Serverless Function File...
2020/12/21 13:01:42 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2020/12/21 13:01:42 QUIC Server listens on 0.0.0.0:4242
^C
```

### Environments

```bash
~/.../yomo/example >>> cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
```

### Solution

Run `sudo sysctl -w net.core.rmem_max=2500000` to solve this problem followed by [quic-go wiki](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size)

**Comment by fanweixiao** [comment]
Unfortunately, on Linux this value is rather small, too small for high-bandwidth QUIC transfers. This buffer holds packets that have been received by the kernel, but not yet read by the application (quic-go in this case). Once this buffer fills up, the kernel will drop any new incoming packet.

**Comment by RubenKelevra** [comment]
> Unfortunately, on Linux this value is rather small, too small for high-bandwidth QUIC transfers. This buffer holds packets that have been received by the kernel, but not yet read by the application (quic-go in this case). Once this buffer fills up, the kernel will drop any new incoming packet.

True. But the user might be interested how to change this:

https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
